### PR TITLE
make scrutinizer happy by removing unused code

### PR DESCRIPTION
**Pull request by Remo**

### CODE REVIEW

**Comment by robertmain** [comment]
"unused code"?

**Comment by Remo** [comment]
if you throw an exception the code afterwards won't be executed

**Comment by Remo** [comment]
https://scrutinizer-ci.com/g/robertmain/communique/issues/master/files/src/CurlHTTPClient.php?selectedLabels%5B0%5D=2&orderField=path&order=asc&honorSelectedPaths=1

**Comment by StrangelyTyped** [comment]
Personally I think it's more readable with the breaks. Regardless of how the switch exits (return, throw, etc) the break is what you instinctively look for when reading it. But you're right they serve no technical purpose

**Comment by robertmain** [comment]
This was my argument initially but having thought about it, I merged due to the code being unreachable.

**Comment by Remo** [comment]
I personally like static code analyzers to find potential problems and the less things I see the better, but I definitely see your point.. 50/50 I'd say.

**Pull request merged**
